# Multinomial Naive Bayes

In [1]:
import numpy as np
from collections import defaultdict
from tqdm import tqdm_notebook

import numpy as np

class MultinomialNaiveBayes:
    def fit(self, X, y):
        # Calculate the number of classes and store the class labels
        self.classes = np.unique(y)
        n_classes = len(self.classes)
        
        # Calculate the number of samples and features
        n_samples, n_features = X.shape
        
        # Calculate the class priors
        self.priors = np.zeros(n_classes)
        for i in range(n_classes):
            #self.priors[i] = 
            pass
        # Calculate the class-conditional feature probabilities
        self.counts = np.zeros((n_classes, n_features))
        for i in range(n_classes):
            X_class = X[y == self.classes[i],:]
            self.counts[i,:] = np.sum(X_class, axis=0) + 1
        self.counts /= np.sum(self.counts, axis=1).reshape(-1, 1) + n_features
        
    def predict(self, X):
        # Calculate the log probability of each class for each sample
        #log_probs = 
        
        # Return the class with the highest log probability for each sample
        return self.classes[np.argmax(log_probs, axis=1)]




In the multinomial Naive Bayes model, each document is represented as a bag of words and the number of occurrences of each word is used as a feature.

Given a set of $m$ training documents, $C$ classes, and a vocabulary of $n$ words, let $x$ be a new document represented as a bag of words, where $x_i$ is the count of the i-th word in the vocabulary in the document. The goal is to find the class $y$ that maximizes the posterior probability, $P(y|x)$, using Bayes' Theorem:

>$P(y|x) = \frac{P(x|y)P(y)}{P(x)}$

Here, $P(y)$ is the prior probability of the class, which can be estimated as the fraction of documents in the training set that belong to class y. $P(x|y)$ is the likelihood of the document given the class, which can be estimated as the product of the probabilities of each word in the vocabulary given the class. $P(x)$ is the normalizing constant, which is the same for all classes and can be ignored for the purposes of estimation.

Using the multinomial distribution, the likelihood can be written as:

>$P(x|y) = \prod_{i=1}^n P(x_i|y)$

Where $P(x_i|y)$ is the probability of observing word $i$ in a document given class $y$, which can be estimated as the count of word $i$ in class $y$ divided by the total count of all words in class $y$.

Finally, taking the log of the posterior probabilities makes the calculation easier and allows us to find the MAP estimate by simply taking the maximum value:

$$
\begin{aligned}
\log P(y|x) &= \log \frac{P(x|y)P(y)}{P(x)} \\
&= \log P(x|y) + \log P(y) - \log P(x) \\
\end{aligned}
$$

For prediction's we can ignore $\log P(x)$ term and report the y that has highest $\log P(y = i|x)$, where $i = {1,\dots,c}$.

Above implementation has two missing parts. Let's develop it step by step.

**Q1: PART A [5 points]**

Before writing any code, consider the following toy input. After fitting the dataset, what should be the value in `self.priors` ?

Note: you need to just write down the answer.

Solution: The self.priors will be 1/2, 1/2. Because as we can see the y has length 4, and there are two 0, and two 1. So the prior should be 2/4 and 2/4, which is 1/2, 1/2



In [2]:
# Example usage

#here we assume n = 4, and each X, say [1,1,2,0] represents the corresponding counts of each of those words in that sentence.
X = np.array([[1, 1, 2, 0], [2, 1, 1, 0], [0, 2, 1, 2], [1, 1, 0, 2]])
# we have two classes 
y = np.array([0, 1, 0, 1])





**Q1: PART B [15 points]**

In the `fit` function fill the missing line by uncommenting `self.priors[i] = ` and also remove `pass` after doing so. 

Note: Make edits in the below template.




In [3]:
class MultinomialNaiveBayes:
    def fit(self, X, y):
        # Calculate the number of classes and store the class labels
        self.classes = np.unique(y)
        n_classes = len(self.classes)
        
        # Calculate the number of samples and features
        n_samples, n_features = X.shape
        
        # Calculate the class priors
        unique, counts = np.unique(y, return_counts=True)
        dic = dict(zip(unique, counts))
        self.priors = np.zeros(n_classes)
        for i in range(n_classes):
            # self.priors[i] = np.log(self.classes[i]/np.sum(self.classes))
            self.priors[i] = dic.get(i)/len(y)
            # pass
        # Calculate the class-conditional feature probabilities
        self.counts = np.zeros((n_classes, n_features))
        for i in range(n_classes):
            X_class = X[y == self.classes[i],:]
            self.counts[i,:] = np.sum(X_class, axis=0) + 1
        self.counts /= np.sum(self.counts, axis=1).reshape(-1, 1) + n_features
        
        # test
        # print()
    def predict(self, X):
        # Calculate the log probability of each class for each sample
        #log_probs = 
        
        # Return the class with the highest log probability for each sample
        return self.classes[np.argmax(log_probs, axis=1)]


In [4]:
nb = MultinomialNaiveBayes()
nb.fit(X, y)


Here fit calculates the p(y) and also stores two sets of parameters p(x|y) for y=0 and y=1. Let's check these before proceeding. (run the below cells)

In [5]:
nb.priors

array([0.5, 0.5])

In [6]:
nb.counts.shape

(2, 4)

In [7]:
nb.counts

array([[0.11764706, 0.23529412, 0.23529412, 0.17647059],
       [0.25      , 0.1875    , 0.125     , 0.1875    ]])

**Q1: PART C [15 points]**

Complete the `log_probs = ` line in predict function. (code block is pasted below)

Note: If you can't implement in a single line you are free to write it in multiple lines. If your implementation is correct below `assert` statement should run with no error.

In [8]:
from numpy.core.memmap import dtype
from scipy.stats import binom, norm

# class MultinomialNaiveBayes:
#     def fit(self, X, y):
#         # Calculate the number of classes and store the class labels
#         self.classes = np.unique(y)
#         n_classes = len(self.classes)
        
#         # Calculate the number of samples and features
#         n_samples, n_features = X.shape
        
#         # Calculate the class priors
#         self.priors = np.zeros(n_classes)
#         for i in range(n_classes):
#             # self.priors[i] = self.classes[i]/np.sum(self.classes)
#             self.priors[i] = self.classes[i]/np.sum(self.classes)
#             # pass
#         # Calculate the class-conditional feature probabilities
#         self.counts = np.zeros((n_classes, n_features))
#         for i in range(n_classes):
#             X_class = X[y == self.classes[i],:]
#             self.counts[i,:] = np.sum(X_class, axis=0) + 1
#             # print(self.counts[i,:])
#         self.counts /= np.sum(self.counts, axis=1).reshape(-1, 1) + n_features
class MultinomialNaiveBayes:
    def fit(self, X, y):
        # Calculate the number of classes and store the class labels
        self.classes = np.unique(y)
        n_classes = len(self.classes)
        
        # Calculate the number of samples and features
        n_samples, n_features = X.shape
        
        # Calculate the class priors
        unique, counts = np.unique(y, return_counts=True)
        dic = dict(zip(unique, counts))
        self.priors = np.zeros(n_classes)
        for i in range(n_classes):
            # self.priors[i] = np.log(self.classes[i]/np.sum(self.classes))
            self.priors[i] = dic.get(i)/len(y)
            # pass
        # Calculate the class-conditional feature probabilities
        self.counts = np.zeros((n_classes, n_features))
        for i in range(n_classes):
            X_class = X[y == self.classes[i],:]
            self.counts[i,:] = np.sum(X_class, axis=0) + 1
        self.counts /= np.sum(self.counts, axis=1).reshape(-1, 1) + n_features
        
        # self.count was [2. 4. 4. 3.], [4. 3. 2. 3.], then each value need to divide the sum + 4
    def predict(self, X):
      # returns a list of class labels for each x in X.
      # Calculate the log probability of each class for each sample
      # 0 has 9 words, 1 has 8 words
      # 2 classes
      
      '''
      
      probs = self.counts.reshape(-1,len(self.counts))
      log_probs = self.counts.reshape(-1,len(self.counts))
      for n in range(len(log_probs)):
        for i in range(len(log_probs[n])):
          log_probs[n][i] = 1
      '''

      log_probs = np.dot(np.log(self.counts), X.T) + np.log(self.priors).reshape(-1, 1)
      log_probs = log_probs.T
      
      '''
      n_class, n_theta = self.counts.shape
      n_samples, n_features = X.shape
      log_probs = []
      likeli = []
      for i in range(n_class):
        for j in range(n_samples):
          # likeli.append(np.log(np.prod(np.power(self.counts[i,:], X[j,:]))))
          likeli.append(np.log(np.prod(np.power(self.counts[i,:], X[j,:]))))
          # print(i, j)
      for i in range(len(likeli)//2):
        log_probs.append([likeli[i] + np.log(self.priors[0]), likeli[i+n_samples]] + np.log(self.priors[1]))
      
      # print(likeli)

      '''
        
      print(log_probs)


        
      # Return the class with the highest log probability for each sample
      return self.classes[np.argmax(log_probs, axis=1)]


In [9]:
#here we assume n = 4, and each X, say [1,1,2,0] represents the corresponding counts of each of those words in that sentence.
X = np.array([[1, 1, 2, 0], [2, 1, 1, 0], [0, 2, 1, 2], [1, 1, 0, 2]])
# we have two classes 
y = np.array([0, 1, 0, 1])

nb = MultinomialNaiveBayes()
nb.fit(X, y)
print(nb.predict(X))
assert np.all(nb.predict(X)==y),"your predictions are wrong"

[[-7.17397029 -7.91230106]
 [-7.86711747 -7.21915388]
 [-8.50310624 -9.46849446]
 [-7.74933444 -7.10137084]]
[0 1 0 1]
[[-7.17397029 -7.91230106]
 [-7.86711747 -7.21915388]
 [-8.50310624 -9.46849446]
 [-7.74933444 -7.10137084]]


Now let's test the effectivness of this algorithm on a real-world data set. 

In [10]:
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer

# Load the 20 Newsgroups dataset
newsgroups_train = fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))
newsgroups_test = fetch_20newsgroups(subset='test', remove=('headers', 'footers', 'quotes'))

#look at the below cells and understand the dataset.

This data set has 20 different types of news

In [11]:
len(newsgroups_train.data)

11314

In [12]:
print(list(newsgroups_train.target_names))

['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


In [13]:
#let's see a sample
newsgroups_train.data[0]

'I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.'

In [14]:
#The target attribute is the integer index of the category
newsgroups_train.target[0],list(newsgroups_train.target_names)[newsgroups_train.target[0]]

(7, 'rec.autos')

**Q2: PART A [15 POINTS]**

Before proceeding, we need to convert the text into Bag of words format(as we saw in toy example). Sklearn has a built in function for it. Read the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) for it below and fill the missing lines

In [15]:
# Convert the text data into a bag-of-words representation
vectorizer = CountVectorizer()
# X_train = vectorizer.fit_transform(newsgroups_train.data)
vectorizer = vectorizer.fit(newsgroups_train.data)
X_train = vectorizer.transform(newsgroups_train.data)
X_test = vectorizer.transform(newsgroups_test.data)
# Note both train and test data are newsgroups_train.data,newsgroups_test.data respectively. 

In [16]:
print(newsgroups_test.data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [17]:
print(X_train)

  (0, 9843)	1
  (0, 11174)	1
  (0, 16809)	1
  (0, 17936)	1
  (0, 18915)	2
  (0, 21987)	1
  (0, 23480)	1
  (0, 24160)	1
  (0, 24635)	1
  (0, 25492)	1
  (0, 25590)	1
  (0, 25775)	4
  (0, 30074)	1
  (0, 31990)	1
  (0, 34809)	1
  (0, 34810)	1
  (0, 35974)	1
  (0, 37287)	1
  (0, 37335)	1
  (0, 41715)	2
  (0, 41724)	1
  (0, 41979)	1
  (0, 45885)	1
  (0, 46814)	1
  (0, 48754)	2
  :	:
  (11313, 57131)	1
  (11313, 60560)	1
  (11313, 61975)	1
  (11313, 62086)	1
  (11313, 64435)	1
  (11313, 66242)	1
  (11313, 66857)	2
  (11313, 68080)	1
  (11313, 68409)	1
  (11313, 68997)	1
  (11313, 70066)	1
  (11313, 71786)	1
  (11313, 71992)	1
  (11313, 78365)	1
  (11313, 81742)	1
  (11313, 81792)	1
  (11313, 82660)	1
  (11313, 84605)	1
  (11313, 85524)	1
  (11313, 87730)	1
  (11313, 89465)	1
  (11313, 89804)	1
  (11313, 90644)	1
  (11313, 96497)	1
  (11313, 96707)	1


**Q2: PART B [15 POINTS]**

If your implementation of all the above parts is correct, you should be able to run the below cell. Fill in the below cell for `accuracy = `and report your result ?

Solution: As we can see the accuracy is 0.46269, which is 46.27%

In [18]:
# Fit the multinomial Naive Bayes model on the training data
mnb = MultinomialNaiveBayes()
mnb.fit(X_train, newsgroups_train.target)

# Predict the class labels of the testing samples
X_test_new = X_test.toarray()
print(mnb.counts.shape)
print(X_test.shape)


y_pred = mnb.predict(X_test_new)

# Calculate the accuracy of the model

# accuracy = np.mean(y_pred == newsgroups_test.target)
# accuracy = np.mean(np.allclose(y_pred, newsgroups_test.target))

accuracy = np.mean(y_pred == newsgroups_test.target) 
print("Accuracy:", accuracy)


(20, 101631)
(7532, 101631)
[[ -664.2190063   -660.98839638  -716.11578155 ...  -642.17683855
   -647.83270231  -674.17707868]
 [ -716.16664562  -695.82606421  -761.2309516  ...  -686.91320203
   -695.86896547  -718.24227467]
 [  -25.92634477   -28.08759149   -28.66156651 ...   -25.45031238
    -25.70026508   -25.77189493]
 ...
 [ -913.98117426  -941.67135634 -1006.36207561 ...  -884.6243752
   -891.05636163  -928.87706045]
 [ -898.22186277  -846.10215284  -907.4944566  ...  -883.64265579
   -885.83110116  -891.79325943]
 [ -484.07346958  -530.47563039  -567.74555625 ...  -497.97914034
   -490.08440267  -497.09983916]]
Accuracy: 0.4626925119490175


In [19]:
y_pred[:10]

array([15, 17, 15, 17,  0, 13, 15, 17,  5, 15])

In [20]:
newsgroups_test.target[:10]

array([ 7,  5,  0, 17, 19, 13, 15, 15,  5,  1])

**Q2: PART C [5 Points]**

In your code for calculating the counts(`self.counts`) 

```
self.counts[i,:] = np.sum(X_class, axis=0) + 1
```

```
 self.counts /= np.sum(self.counts, axis=1).reshape(-1, 1) + n_features
 ```

 Why do we add 1 in the numerator and include n_features ? Give a short explanation ?

 Hint: It's called Laplace smoothing. Figure out why it's being used here.

Solution:
The reason we add 1 in the numerator and include n_features is because we want to avoid the zero-counts. If we don't have a word in the class, then the count of this word will be 0. When we calculate log probability of this nonexist word, it will become -inf. In this case we will add 1 to all the count. Same logic for add the n_features, we know that np.sum(self.counts, axis=1).reshape(-1, 1) represent total count of each class. So we want to add n_features to the denominator to avoid zero-counts.


# Logistic Regression









Consider this data set

| Feature 1 | Feature 2 | Class |
|-----------|-----------|-------|
| 1         | 1         | 0     |
| 2.2         | 1.6         | 0     |
| 2.5         | 1.8         | 0     |
| 2.8         | 1.5         | 0     |
| 2.9         | 1.2         | 0     |
| 3.0        | 3.0        | 1     |


Consider the above data and train a logistic regression model on this data.

Here are the learned weights: 
> $w_0$=  -4.08673095

> $w_1$= 0.33123783

> $w_2$= 0.89782125

>Here $w_0$ corresponds to the intercept.

</br>

Here are the equations we discussed for class-conditional probabilities on a data-point $x_i = [x_{i1}, x_{i2}, ..., x_{ip}]$ :

>$ P(y=1|\mathbf{x_i}) = \frac{1}{1 + e^{z}} $ 

>$ P(y=0|\mathbf{x_i}) = \frac{e^{z}}{1 + e^{z}} $ 

>Where $z = w_0 + w_1 x_{i1} + w_2 x_{i2} + ... + w_p x_{ip}$

>Here $w_0$ is the intercept, $w_1, w_2, ..., w_p$ are the coefficients of the predictor variables $x_{i1}, x_{i2}, ..., x_{ip}$ for the $i$-th training sample, respectively.

**Q3: PART A [10 points]**

What is the accuracy over training data? (show the steps)

**Q3: PART B [10 points]**

Is the decision boundary linear or non-linear (5 points)? 

Please write down the expression for the decision boundary (5 points).

**Q3: PART C [10 points]**

List all the classifiers we have learned, that are generative classifiers. What are their properties? (5 points)

List all the classifiers we have learned that are discriminative classifiers. What are their properties? (5 points)

Solution:

part A:
The accuracy will be 1/6, 16.67%. Because due to the calculation all samples should be in class 1. Steps are in the pdf

part B:
The decision boundary should be linear. The expression of the decision bounary is $z = w_0 + w_1 x_{i1} + w_2 x_{i2} + ... + w_p x_{ip}$, where $w_0$=  -4.08673095, $w_1$= 0.33123783, $w_2$= 0.89782125. So our expression will be z = -4.08673095 + 0.33123783 * $x_{i1}$ + 0.89782125 * $x_{i2}$

part C:

For generative classifiers we learned: Naive Bayes which assume that all features are conditional independent. Probability table

Generative classifiers is about estimate parameters of P(X|Y). The properties of generative classifiers is that we view P(X|Y) as describing how to sample random instance X given Y. Also, after we model the distribution of the input for each class, we can generate new samples for each class.

For discriminative classifiers we learned: logistic regression, decision tree

Discriminative classifiers is about estimate parameters of P(Y|X). The properties are we do not care how instances are generated. We can also learn a decision boundary directly from training data. Different from the generative classifiers, we cannot generate new samples using discriminative classifiers.